- name: Install the latest version of mongodb
  ansible.builtin.dnf:
    name: mongodb-org
    state: installed

- name: Copy mongo repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Replace the IP address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start service mongod
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: true




