- name: Disable redis
  ansible.builtin.shell: dnf module disable redis -y

- name: Enable redis
  ansible.builtin.shell: dnf module enableredis:7 -y

- name: Install the latest version of redis
  ansible.builtin.dnf:
    name: redis
    state: installed


- name: Replace the IP address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Replace the IP address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: Start service redis
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: true


