- name: Install the latest version of mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start service mysqld
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Set mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1



