
- name: Disable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install the latest version of nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Install maven dependencies
  community.general.npm:
    path: /app

- name: Add the user roboshop
  become: yes
  ansible.builtin.user:
    name: roboshop
    state: present

- name: Copy catalogue.service file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
    remote_src: yes

- name:  Remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: directory


- name: Downoad catalogue content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /app
    remote_src: yes

- name: Include systemd
  ansible.builtin.include_tasks:
    file: systemd.yml
