
- name: Disable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install the latest version of nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Install maven dependencies
  community.general.npm:
    path: /app

- name: Add the user roboshop
  ansible.builtin.user:
    name: roboshop
    become: yes

- name: Copy "{{app_name}}".service file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/"{{app_name}}".service

- name:  Remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: directory


- name: Downoad "{{app_name}}" content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/"{{app_name}}"-v3.zip
    dest: /app
    remote_src: yes

- name: Include systemd
  ansible.builtin.include_tasks:
    file: systemd.yml
